/*

 OMEGA.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 10
   Tile set      : Z:\home\torch2424\Source\radical-rumble-robots\src\scenes\battle\tiles\Platforms.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define OmegaWidth 10
#define OmegaHeight 10
#define OmegaBank 0

extern unsigned char Omega[];

/* End of OMEGA.H */
